---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---
```{r}
library(dplyr)
library(MASS)
library(gam)
library(mgcv)


data <- read.csv("C:/Users/matth/OneDrive/Desktop/Books/Thesis/freMTPL2freq.csv", header = TRUE)

df <- data %>%
  mutate(
    ClaimFreq = ClaimNb / Exposure,
    VehBrand = as.factor(VehBrand),
    VehGas   = as.factor(VehGas),
    Area     = as.factor(Area),
    Region   = as.factor(Region)
  )

names(df)
```

```{r}

glm_poisson <- glm(
  ClaimNb ~ VehPower + VehAge + DrivAge + BonusMalus +
            VehBrand + VehGas + Area + Density + Region,
  offset = log(Exposure),
  family = poisson(link = "log"),
  data = df
)

#summary(glm_poisson)
anova(glm_poisson)
```

```{r}
dispersion <- sum(residuals(glm_poisson, type = "pearson")^2) / df.residual(glm_poisson)
dispersion
```

```{r}
glm_nb <- glm.nb(
  ClaimNb ~ VehPower + VehAge + DrivAge + BonusMalus +
            VehBrand + VehGas + Area + Density + Region +
            offset(log(Exposure)),
  data = df
)
anova(glm_nb)
```

```{r}
library(splines)

glm_spline <- glm(
  ClaimNb ~ VehPower +
            ns(VehAge, 3) +
            ns(DrivAge, 3) +
            ns(BonusMalus, 3) +
            VehBrand + VehGas + Area + Density + Region,
  offset = log(Exposure),
  family = poisson,
  data = df
)
anova(glm_spline)
```

```{r}
df$pred_glm <- predict(glm_poisson, type = "response")
df$freq_glm <- df$pred_glm / df$Exposure

summary(df$pred_glm)
summary(df$freq_glm)

```

```{r}
AIC(glm_poisson, glm_nb,glm_spline)
```

